- hosts: all
  tasks:
    - name: upgrade apt packages
      become: yes
      
      apt:
        upgrade: yes
        update_cache: yes
        
- hosts: localhost
  vars:
    ansible_host_key_checking: false

