- hosts: all
  tasks:
    - name: packages | ensure apt list dir exists
      file:
      path: /var/lib/apt/lists/
      state: directory
      mode: 0755
    - name: upgrade apt packages
      become: true
      become_method: su
      become_user: root
      apt:
        upgrade: yes
        update_cache: yes
