---
- name: Example Playbook to Become Root
  hosts: all
  become: true  # This enables privilege escalation, i.e., executing commands as root

  tasks:
    - name: Execute command to become root
      shell: su -
      register: root_user_result

    - name: Debug root user
      debug:
        msg: "Current user is {{ root_user_result.stdout }}"
