---
- name: Example Playbook to Execute Commands as Root
  hosts: all
  become: true  # This enables privilege escalation, i.e., executing commands as root

  tasks:
    - name: Debug root user
      command: whoami
      register: root_user_result

    - name: Display current user
      debug:
        msg: "Current user is {{ root_user_result.stdout }}"
