---
- name: APT Update with Retry
  hosts: all
  become: true  # Use sudo for privilege escalation

  tasks:
    - name: Check APT Lock File
      command: "fuser /var/lib/apt/lists/lock"
      register: apt_lock_status
      ignore_errors: true

    - name: Wait for APT Lock to be Released
      pause:
        seconds: 10  # Adjust the delay as needed
      until: "apt_lock_status.rc != 0"
      retries: 6
      delay: 10

    - name: APT Update
      apt:
        update_cache: yes
